### ISSUE TITLE
latest kube-proxy doesn't fail-fast if proxier creation fails

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#107]
Instead it panics. Observed in kubernetes v0.6.2:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b4e17]

goroutine 7 [running]:
runtime.panic(0x737600, 0xbe0028)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.(*Proxier).getServiceInfo(0x0, 0xc2100a68e0, 0xa, 0x0, 0x0)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:386 +0xc7
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.(*Proxier).OnUpdate(0x0, 0xc21010a200, 0x6, 0x8)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:445 +0x28d
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/config.func·005(0x68d640, 0xc210048e20)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/config/config.go:188 +0x79
github.com/GoogleCloudPlatform/kubernetes/pkg/util/config.ListenerFunc.OnUpdate(0xc21008df30, 0x68d640, 0xc210048e20)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/config/config.go:110 +0x36
github.com/GoogleCloudPlatform/kubernetes/pkg/util/config.(*Watcher).Notify(0xc2100802a0, 0x68d640, 0xc210048e20)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/config/config.go:138 +0xb9
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/config.watchForUpdates(0xc2100802a0, 0x7f69f4fce3a8, 0xc2100801e0, 0xc210037780)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/config/config.go:266 +0x88
created by github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/config.NewServiceConfig
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/config/config.go:182 +0x196
```

**Comment by jdef** [comment]
implicitly resolved by #124
