### ISSUE TITLE
flakey executor test

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#351]
see changes for upstream PR that backed out the flakey unit test.
- https://github.com/GoogleCloudPlatform/kubernetes/pull/9767

sample test logs when for the failing case:
```
ok  	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/scheduler/podtask	1.123s	coverage: 69.9% of statements
I0612 18:10:18.811021    7077 executor_test.go:127] resetting suicide watch with 1 task
I0612 18:10:18.811721    7077 executor_test.go:149] resetting suicide watch with 0 tasks
I0612 18:10:18.812051    7077 executor.go:385] resetting suicide watch timer for 1.5s
I0612 18:10:18.812201    7077 executor_test.go:171] resetting suicide watch with 1 task
I0612 18:10:18.812461    7077 executor.go:335] stopping suicide watch
I0612 18:10:18.812549    7077 executor_test.go:193] resetting suicide watch with 0 tasks
I0612 18:10:18.814141    7077 executor.go:346] resetting suicide watch
W0612 18:10:20.316235    7077 executor.go:325] Suicide timeout (1.5s) expired
W0612 18:10:20.316380    7077 executor_test.go:81] jumping?!
I0612 18:10:21.811995    7077 executor_test.go:216] jumps verified
I0612 18:10:21.813758    7077 executor.go:210] Executor nil of framework nil registered with slave nil
I0612 18:10:21.817138    7077 executor.go:210] Executor nil of framework nil registered with slave nil
I0612 18:10:21.817333    7077 executor.go:252] Slave is disconnected
I0612 18:10:21.818494    7077 executor.go:210] Executor nil of framework nil registered with slave nil
I0612 18:10:21.818639    7077 executor.go:252] Slave is disconnected
I0612 18:10:21.818725    7077 executor.go:226] Reregistered with slave nil
I0612 18:10:21.821616    7077 executor.go:210] Executor nil of framework nil registered with slave nil
I0612 18:10:21.833480    7077 executor.go:266] Launch task &TaskInfo{Name:*pod1.default.pods,TaskId:&TaskID{Value:*pod.4a59a3da-112e-11e5-826b-0242ac110515,XXX_unrecognized:[],},SlaveId:&SlaveID{Value:*,XXX_unrecognized:[],},Resources:[&Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*0,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],} &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*0,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],}],Executor:&ExecutorInfo{ExecutorId:nil,FrameworkId:nil,Command:nil,Container:nil,Resources:[],Name:nil,Source:nil,Data:nil,XXX_unrecognized:[],},Command:nil,Container:nil,Data:*[123 34 107 105 110 100 34 58 34 80 111 100 34 44 34 97 112 105 86 101 114 115 105 111 110 34 58 34 118 49 98 101 116 97 51 34 44 34 109 101 116 97 100 97 116 97 34 58 123 34 110 97 109 101 34 58 34 112 111 100 49 34 44 34 110 97 109 101 115 112 97 99 101 34 58 34 100 101 102 97 117 108 116 34 44 34 115 101 108 102 76 105 110 107 34 58 34 47 97 112 105 47 118 49 98 101 116 97 51 47 112 111 100 115 47 92 117 48 48 48 49 34 44 34 99 114 101 97 116 105 111 110 84 105 109 101 115 116 97 109 112 34 58 110 117 108 108 125 44 34 115 112 101 99 34 58 123 34 99 111 110 116 97 105 110 101 114 115 34 58 91 123 34 110 97 109 101 34 58 34 34 44 34 105 109 97 103 101 34 58 34 34 44 34 112 111 114 116 115 34 58 91 123 34 99 111 110 116 97 105 110 101 114 80 111 114 116 34 58 56 48 48 49 44 34 112 114 111 116 111 99 111 108 34 58 34 84 67 80 34 125 93 44 34 114 101 115 111 117 114 99 101 115 34 58 123 125 44 34 99 97 112 97 98 105 108 105 116 105 101 115 34 58 123 125 125 93 125 44 34 115 116 97 116 117 115 34 58 123 34 67 111 110 100 105 116 105 111 110 34 58 91 123 34 116 121 112 101 34 58 34 82 101 97 100 121 34 44 34 115 116 97 116 117 115 34 58 34 84 114 117 101 34 125 93 125 125],HealthCheck:nil,XXX_unrecognized:[],}
I0612 18:10:21.837177    7077 executor.go:460] Binding 'default/pod1' to '' with annotations map[]...
I0612 18:10:22.146494    7077 executor.go:685] Kill task &TaskID{Value:*pod.4a59a3da-112e-11e5-826b-0242ac110515,XXX_unrecognized:[],}
I0612 18:10:22.176417    7077 executor.go:210] Executor nil of framework nil registered with slave nil
I0612 18:10:22.184033    7077 executor.go:753] Receives message from framework test framework message
I0612 18:10:22.185374    7077 executor.go:266] Launch task &TaskInfo{Name:*pod1.default.pods,TaskId:&TaskID{Value:*foo,XXX_unrecognized:[],},SlaveId:&SlaveID{Value:*,XXX_unrecognized:[],},Resources:[&Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*0,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],} &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*0,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],}],Executor:&ExecutorInfo{ExecutorId:nil,FrameworkId:nil,Command:nil,Container:nil,Resources:[],Name:nil,Source:nil,Data:nil,XXX_unrecognized:[],},Command:nil,Container:nil,Data:*[123 34 107 105 110 100 34 58 34 80 111 100 34 44 34 97 112 105 86 101 114 115 105 111 110 34 58 34 118 49 98 101 116 97 51 34 44 34 109 101 116 97 100 97 116 97 34 58 123 34 110 97 109 101 34 58 34 112 111 100 49 34 44 34 110 97 109 101 115 112 97 99 101 34 58 34 100 101 102 97 117 108 116 34 44 34 115 101 108 102 76 105 110 107 34 58 34 47 97 112 105 47 118 49 98 101 116 97 51 47 112 111 100 115 47 92 117 48 48 48 49 34 44 34 99 114 101 97 116 105 111 110 84 105 109 101 115 116 97 109 112 34 58 110 117 108 108 125 44 34 115 112 101 99 34 58 123 34 99 111 110 116 97 105 110 101 114 115 34 58 91 123 34 110 97 109 101 34 58 34 34 44 34 105 109 97 103 101 34 58 34 34 44 34 112 111 114 116 115 34 58 91 123 34 99 111 110 116 97 105 110 101 114 80 111 114 116 34 58 56 48 48 49 44 34 112 114 111 116 111 99 111 108 34 58 34 84 67 80 34 125 93 44 34 114 101 115 111 117 114 99 101 115 34 58 123 125 44 34 99 97 112 97 98 105 108 105 116 105 101 115 34 58 123 125 125 93 125 44 34 115 116 97 116 117 115 34 58 123 34 67 111 110 100 105 116 105 111 110 34 58 91 123 34 116 121 112 101 34 58 34 82 101 97 100 121 34 44 34 115 116 97 116 117 115 34 58 34 84 114 117 101 34 125 93 125 125],HealthCheck:nil,XXX_unrecognized:[],}
I0612 18:10:22.188679    7077 executor.go:753] Receives message from framework task-lost:foo
W0612 18:10:22.189130    7077 executor.go:720] Cannot remove unknown pod  for task foo
I0612 18:10:22.189396    7077 executor.go:460] Binding 'default/pod1' to '' with annotations map[]...
panic: 

mock: Unexpected Method Call
-----------------------------

SendStatusUpdate(mesosproto.TaskState)
		0: TASK_FAILED

The closest call I have is: 

SendStatusUpdate(mesosproto.TaskState)
		0: TASK_LOST


goroutine 72 [running]:
runtime.panic(0xdb32a0, 0xc2082a8310)
	/root/.gvm/gos/go1.3/src/pkg/runtime/panic.c:279 +0xf5
github.com/stretchr/testify/mock.(*Mock).Called(0xc208211340, 0xc2082a80d0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/stretchr/testify/mock/mock.go:266 +0x48b
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*MockExecutorDriver).SendStatusUpdate(0xc208211340, 0xc20822af80, 0x5, 0x0, 0x0)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/mock_test.go:58 +0x10f
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.func·011(0x198a19c, 0x0, 0x0)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:884 +0xb4
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc20825fe10)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:933 +0x46a
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:180 +0x8a

goroutine 16 [chan receive]:
testing.RunTests(0x12949d8, 0x1970be0, 0xa, 0xa, 0x1)
	/root/.gvm/gos/go1.3/src/pkg/testing/testing.go:505 +0xbb8
testing.Main(0x12949d8, 0x1970be0, 0xa, 0xa, 0x19a7860, 0x0, 0x0, 0x19a7860, 0x0, 0x0)
	/root/.gvm/gos/go1.3/src/pkg/testing/testing.go:435 +0xa3
main.main()
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_testmain.go:113 +0x18c

goroutine 19 [finalizer wait]:
runtime.park(0x4366c0, 0x199f2f0, 0x19772a9)
	/root/.gvm/gos/go1.3/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x199f2f0, 0x19772a9)
	/root/.gvm/gos/go1.3/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/root/.gvm/gos/go1.3/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/root/.gvm/gos/go1.3/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/root/.gvm/gos/go1.3/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x19a3560)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x96
created by github.com/golang/glog.init·1
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2d6

goroutine 30 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.3/src/pkg/os/signal/signal_unix.go:21 +0x2c
created by os/signal.init·1
	/root/.gvm/gos/go1.3/src/pkg/os/signal/signal_unix.go:27 +0x40

goroutine 45 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc20823a9c0)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:926 +0x3b6
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:180 +0x8a

goroutine 48 [select]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc2080008f0)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:916 +0x34d
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:180 +0x8a

goroutine 51 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc208001380)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:926 +0x3b6
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:180 +0x8a

goroutine 54 [select]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0xc208224600, 0x1)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0xf8
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc208224600)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x35
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x8d

goroutine 56 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc208001ee0)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:926 +0x3b6
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:180 +0x8a

goroutine 70 [select]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0xc2081c9580, 0x7f333c0a3101)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0xf8
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc2081c9580)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x35
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x8d

goroutine 69 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.TestExecutorFrameworkMessage(0xc20805d710)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/executor_test.go:462 +0xffe
testing.tRunner(0xc20805d710, 0x1970c70)
	/root/.gvm/gos/go1.3/src/pkg/testing/testing.go:422 +0x110
created by testing.RunTests
	/root/.gvm/gos/go1.3/src/pkg/testing/testing.go:504 +0xb46
FAIL	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor	4.610s
```

**Comment by jdef** [comment]
merged upstream
