### ISSUE TITLE
TestExecutorLaunchAndKillTask is flakey

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#352]
It's causing failures in shippable builds upstream (it's breaking the build for https://github.com/GoogleCloudPlatform/kubernetes/pull/9741)

```
I0613 21:37:00.329797    6854 executor_test.go:127] resetting suicide watch with 1 task
I0613 21:37:00.330780    6854 executor_test.go:149] resetting suicide watch with 0 tasks
I0613 21:37:00.331197    6854 executor.go:405] resetting suicide watch timer for 1.5s
I0613 21:37:00.331472    6854 executor_test.go:171] resetting suicide watch with 1 task
I0613 21:37:00.331850    6854 executor.go:350] stopping suicide watch
I0613 21:37:00.332055    6854 executor_test.go:193] resetting suicide watch with 0 tasks
I0613 21:37:00.332497    6854 executor.go:362] resetting suicide watch
W0613 21:37:01.833041    6854 executor.go:340] Suicide timeout (1.5s) expired
W0613 21:37:01.833163    6854 executor_test.go:81] jumping?!
I0613 21:37:03.331009    6854 executor_test.go:216] jumps verified
I0613 21:37:03.332183    6854 executor.go:215] Executor nil of framework nil registered with slave nil
I0613 21:37:03.333661    6854 executor.go:215] Executor nil of framework nil registered with slave nil
I0613 21:37:03.333787    6854 executor.go:260] Slave is disconnected
I0613 21:37:03.335087    6854 executor.go:215] Executor nil of framework nil registered with slave nil
I0613 21:37:03.335204    6854 executor.go:260] Slave is disconnected
I0613 21:37:03.335289    6854 executor.go:233] Reregistered with slave nil
I0613 21:37:03.338241    6854 executor.go:215] Executor nil of framework nil registered with slave nil
I0613 21:37:03.344201    6854 executor.go:280] Launch task &TaskInfo{Name:*pod1.default.pods,TaskId:&TaskID{Value:*pod.54a49a22-1214-11e5-8b30-0242ac110692,XXX_unrecognized:[],},SlaveId:&SlaveID{Value:*,XXX_unrecognized:[],},Resources:[&Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*0,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],} &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*0,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],}],Executor:&ExecutorInfo{ExecutorId:nil,FrameworkId:nil,Command:nil,Container:nil,Resources:[],Name:nil,Source:nil,Data:nil,XXX_unrecognized:[],},Command:nil,Container:nil,Data:*[123 34 107 105 110 100 34 58 34 80 111 100 34 44 34 97 112 105 86 101 114 115 105 111 110 34 58 34 118 49 34 44 34 109 101 116 97 100 97 116 97 34 58 123 34 110 97 109 101 34 58 34 112 111 100 49 34 44 34 110 97 109 101 115 112 97 99 101 34 58 34 100 101 102 97 117 108 116 34 44 34 115 101 108 102 76 105 110 107 34 58 34 47 97 112 105 47 118 49 47 112 111 100 115 47 92 117 48 48 48 49 34 44 34 99 114 101 97 116 105 111 110 84 105 109 101 115 116 97 109 112 34 58 110 117 108 108 125 44 34 115 112 101 99 34 58 123 34 99 111 110 116 97 105 110 101 114 115 34 58 91 123 34 110 97 109 101 34 58 34 34 44 34 112 111 114 116 115 34 58 91 123 34 99 111 110 116 97 105 110 101 114 80 111 114 116 34 58 56 48 48 49 44 34 112 114 111 116 111 99 111 108 34 58 34 84 67 80 34 125 93 44 34 114 101 115 111 117 114 99 101 115 34 58 123 125 125 93 125 44 34 115 116 97 116 117 115 34 58 123 34 99 111 110 100 105 116 105 111 110 115 34 58 91 123 34 116 121 112 101 34 58 34 82 101 97 100 121 34 44 34 115 116 97 116 117 115 34 58 34 84 114 117 101 34 125 93 125 125],HealthCheck:nil,XXX_unrecognized:[],}
I0613 21:37:03.346436    6854 executor.go:481] Binding 'default/pod1' to '' with annotations map[]...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5f397a]

goroutine 49 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Kubelet).GetNode(0xc2081fd400, 0x0, 0x0, 0x0)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/kubelet.go:633 +0xaa
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Kubelet).GetHostIP(0xc2081fd400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/kubelet.go:1759 +0x80
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.func·005(0xc20801bfd8, 0x0, 0x0)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:551 +0x281
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.func·007(0x0, 0x0, 0x0, 0x0)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:577 +0xf5
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor)._launchTask(0xc208220a90, 0x7fdfbd956de0, 0xc208210770, 0xc20820bbc0, 0x28, 0xc208118b30, 0xc, 0xc208170240)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:630 +0x5f3
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).launchTask
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:564 +0x1bca

goroutine 1 [chan receive]:
testing.RunTests(0x129f808, 0x18b4560, 0xa, 0xa, 0xc20809cf01)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc208208af0, 0x225fb40)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_testmain.go:118 +0x382

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x22573c0)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x99
created by github.com/golang/glog.init·1
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ca

goroutine 15 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x2d
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x43

goroutine 38 [IO wait]:
net.(*pollDesc).Wait(0xc208210760, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x63
net.(*pollDesc).WaitRead(0xc208210760, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x51
net.(*netFD).accept(0xc208210700, 0x0, 0x7fdfbd953dc8, 0xc208118638)
	/usr/local/go/src/net/fd_unix.go:419 +0x4bd
net.(*TCPListener).AcceptTCP(0xc20802e6c8, 0xc2081901e0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x80
net.(*TCPListener).Accept(0xc20802e6c8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x5a
net/http/httptest.(*historyListener).Accept(0xc20820b920, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/httptest/server.go:48 +0xa1
net/http.(*Server).Serve(0xc208218780, 0x7fdfbd9580e8, 0xc20820b920, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0xa3
created by net/http/httptest.(*Server).Start
	/usr/local/go/src/net/http/httptest/server.go:109 +0x4d7

goroutine 37 [select]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.TestExecutorLaunchAndKillTask(0xc20804eb40)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/executor_test.go:380 +0x1e75
testing.tRunner(0xc20804eb40, 0x18b45d8)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e

goroutine 30 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc208220000)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:978 +0x424
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:184 +0x8c

goroutine 33 [select]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc208220270)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:968 +0x3b9
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:184 +0x8c

goroutine 36 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc2082205b0)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:978 +0x424
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:184 +0x8c

goroutine 39 [select]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0xc20820c8c0, 0x44ce01)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0x143
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc20820c8c0)
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x36
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x8f

goroutine 46 [IO wait]:
net.(*pollDesc).Wait(0xc208211790, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x63
net.(*pollDesc).WaitRead(0xc208211790, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x51
net.(*netFD).Read(0xc208211730, 0xc208237000, 0x1000, 0x1000, 0x0, 0x7fdfbd953dc8, 0xc208118730)
	/usr/local/go/src/net/fd_unix.go:242 +0x4b3
net.(*conn).Read(0xc20802ecd8, 0xc208237000, 0x1000, 0x1000, 0x465cb2, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0x125
net.(*TCPConn).Read(0xc20802ecd8, 0xc208237000, 0x1000, 0x1000, 0x129fc40, 0x0, 0x0)
	<autogenerated>:36 +0x86
net/http.noteEOFReader.Read(0x7fdfbd959eb8, 0xc20802ecd8, 0xc2081d6aa8, 0xc208237000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x7c
net/http.(*noteEOFReader).Read(0xc20801eb80, 0xc208237000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:125 +0xfc
bufio.(*Reader).fill(0xc208219080)
	/usr/local/go/src/bufio/bufio.go:97 +0x382
bufio.(*Reader).Peek(0xc208219080, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0x199
net/http.(*persistConn).readLoop(0xc2081d6a50)
	/usr/local/go/src/net/http/transport.go:842 +0xff
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0x10d4

goroutine 41 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).sendLoop(0xc208220a90)
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:978 +0x424
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor.(*KubernetesExecutor).Init
	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/_test/_obj_test/executor.go:184 +0x8c

goroutine 48 [IO wait]:
net.(*pollDesc).Wait(0xc208211870, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x63
net.(*pollDesc).WaitRead(0xc208211870, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x51
net.(*netFD).Read(0xc208211810, 0xc2081fb000, 0x1000, 0x1000, 0x0, 0x7fdfbd953dc8, 0xc2081186e8)
	/usr/local/go/src/net/fd_unix.go:242 +0x4b3
net.(*conn).Read(0xc20802ece8, 0xc2081fb000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0x125
net.(*TCPConn).Read(0xc20802ece8, 0xc2081fb000, 0x1000, 0x1000, 0x18b8e56, 0x0, 0x0)
	<autogenerated>:36 +0x86
net/http.(*liveSwitchReader).Read(0xc208190228, 0xc2081fb000, 0x1000, 0x1000, 0xc208192072, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xcf
io.(*LimitedReader).Read(0xc20801ede0, 0xc2081fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0x18a
bufio.(*Reader).fill(0xc208219200)
	/usr/local/go/src/bufio/bufio.go:97 +0x382
bufio.(*Reader).ReadSlice(0xc208219200, 0xdd0c0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x60c
bufio.(*Reader).ReadLine(0xc208219200, 0x0, 0x0, 0x0, 0x465800, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x7c
net/textproto.(*Reader).readLineSlice(0xc20820a1e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0xc0
net/textproto.(*Reader).ReadLine(0xc20820a1e0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x5d
net/http.ReadRequest(0xc208219200, 0xc2081f4b60, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xdc
net/http.(*conn).readRequest(0xc2081901e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x3dd
net/http.(*conn).serve(0xc2081901e0)
	/usr/local/go/src/net/http/server.go:1162 +0x976
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x3cd

goroutine 50 [semacquire]:
sync.(*WaitGroup).Wait(0xc2080b14a0)
	/usr/local/go/src/sync/waitgroup.go:132 +0x1e8
sync.*WaitGroup.Wait·fm()
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor/executor_test.go:379 +0x35
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/runtime.func·007()
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/runtime/util.go:95 +0xae
created by github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/runtime.After
	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/runtime/util.go:97 +0x159

goroutine 47 [select]:
net/http.(*persistConn).writeLoop(0xc2081d6a50)
	/usr/local/go/src/net/http/transport.go:945 +0x4ff
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0x10f1
FAIL	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/executor	4.146s
```

**Comment by jdef** [comment]
marked as WIP, will be resolved when upstream PR 9741 is merged

**Comment by jdef** [comment]
merged upstream
