### ISSUE TITLE
executor panics with 'index out of range' in GetDockerPodInfo

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#77]
```
I1115 20:13:33.985692 11563 log.go:151] GET /podInfo?podID=bc36de76-6d03-11e4-8ed7-04012f416701: (245.435432ms) 404
panic: runtime error: index out of range

goroutine 513 [running]:
runtime.panic(0x7f2620, 0xc7cf1c)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/dockertools.GetDockerPodInfo(0x7f9d197119a0, 0xc20804ab00, 0xc208a15470, 0x2a, 0xc20817d8f0, 0x24, 0xc208f91a90, 0x0, 0x0)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/dockertools/docker.go:218 +0x500
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Kubelet).GetPodInfo(0xc20808e0c0, 0xc208a15470, 0x2a, 0xc20817d8f0, 0x24, 0xc2086245d0, 0x0, 0x0)
        /pkg/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/kubelet.go:756 +0x7d
github.com/mesosphere/kubernetes-mesos/executor.func·001(0xc20817d8c0, 0x24, 0xc20934bed8, 0x0, 0x0)
        /pkg/src/github.com/mesosphere/kubernetes-mesos/executor/executor.go:123 +0xe4
github.com/mesosphere/kubernetes-mesos/executor.func·002(0xc208005118)
        /pkg/src/github.com/mesosphere/kubernetes-mesos/executor/executor.go:174 +0x34
github.com/mesosphere/kubernetes-mesos/executor.(*KubernetesExecutor).checkForLostPodTask(0xc2080050e0, 0xc2082f1a40, 0xc208297e60, 0xc20813c300)
        /pkg/src/github.com/mesosphere/kubernetes-mesos/executor/executor.go:203 +0x86
github.com/mesosphere/kubernetes-mesos/executor.func·003()
        /pkg/src/github.com/mesosphere/kubernetes-mesos/executor/executor.go:182 +0x6c
created by github.com/mesosphere/kubernetes-mesos/executor.func·004
        /pkg/src/github.com/mesosphere/kubernetes-mesos/executor/executor.go:186 +0x6ae
```

There are a TON of goroutines running. About **80** go routines are in a call to `checkForLostPodTask`. Couple of things come to mind:

* something about this may be racy
* `checkForLostPodTask` is not exiting when it should, since in my small cluster there is only 1 active pod at a time on each slave (for a total of 3 in the cluster)

**Comment by jdef** [comment]
merged upstream #124
